version: "3.8"

services:
  redis:
    image: redis:7-alpine
    hostname: redis
    container_name: cache
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.4GB'
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no --tcp-keepalive 300
  postgres:
    image: postgres:14
    hostname: postgres
    container_name: db-pessoas
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: super-secret
      POSTGRES_DB: people
      PGDATA: /var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d people -U user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: 'postgres -c max_connections=200 -c shared_buffers=512MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
  api1: &api # API - Instância 01
    image: flavio1110/rinha-backend:local
    environment:
      - HTTP_PORT=8080
      - DB_URL=postgres://user:super-secret@postgres:5432/people?sslmode=disable
      - DB_MAX_CONNECTIONS=100
      - DB_MIN_CONNECTIONS=50
      - REDIS_ADDR=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.25GB'
    healthcheck:
      test: curl -o /dev/null -s --retry 0 --head http://localhost:8080/contagem-pessoas || exit 1
      interval: 2s
      retries: 10
      start_period: 20s
      timeout: 5s
  api2: # API - Instância 02
    <<: *api
  nginx: # Load Balancer
    image: nginx:latest
    environment:
      - WAIT_HOSTS=api:8081 api:8082
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: "0.1GB"
    healthcheck:
      test: curl --fail http://localhost:9999/contagem-pessoas
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s