version: "3.8"

services:
  postgres:
    image: postgres:14
    hostname: postgres
    container_name: db-pessoas
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: super-secret
      POSTGRES_DB: people
      PGDATA: /var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.9GB'
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d people -U user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "max_connections=250"
      - "-c"
      - "shared_buffers=256MB"
  api1: # API - Instância 01
    image: flavio1110/rinha-backend:local
    hostname: api1
    environment:
      - HTTP_PORT=8081
      - DB_URL=postgres://user:super-secret@postgres:5432/people?sslmode=disable
      - DB_MAX_CONNECTIONS=100
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "8081"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  api2: # API - Instância 01
    image: flavio1110/rinha-backend:local
    hostname: api2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - HTTP_PORT=8082
      - DB_URL=postgres://user:super-secret@postgres:5432/people?sslmode=disable
      - DB_MAX_CONNECTIONS=100
    expose:
      - "8082"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  nginx: # Load Balancer
    image: nginx:latest
    environment:
      - WAIT_HOSTS=api:8081 api:8082
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.1GB'
    healthcheck:
      test: curl --fail http://localhost:9999/contagem-pessoas
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s