name: Lint Build Test

on:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: .
          version: latest

  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: make tests
  load-tests:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ github.repository_owner }}
          echo ${{ github.repository }}
          echo "GH_USERNAME=$(echo ${{ github.repository }} | cut -d "/" -f 1)" >> $GITHUB_ENV
          echo "GH_REPO=$(echo ${{ github.repository }} | cut -d "/" -f 2)" >> $GITHUB_ENV
      - run: |
          echo ${{ env.GH_REPO }}
          echo ${{ env.GH_USERNAME }}
      - run: make compose-up
      - name: Load test
        run: |
          git clone --single-branch --quiet https://github.com/zanfranceschi/rinha-de-backend-2023-q3
          cd rinha-de-backend-2023-q3
          wget https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.9.5/gatling-charts-highcharts-bundle-3.9.5-bundle.zip
          unzip gatling-charts-highcharts-bundle-3.9.5-bundle.zip
          cd gatling-charts-highcharts-bundle-3.9.5
          ./bin/gatling.sh -rm local -s RinhaBackendSimulation -rd "DESCRICAO" -rf $WORKSPACE/user-files/results -sf $WORKSPACE/user-files/simulations -rsf $WORKSPACE/user-files/resources
          echo GATLING_OUTPUT_FOLDER=$(ls $WORKSPACE/user-files/results | sort | head -n 1) >> $GITHUB_ENV
        env:
          WORKSPACE: ${{ github.workspace }}/rinha-de-backend-2023-q3/stress-test
      - run: echo ${{ env.GATLING_OUTPUT_FOLDER }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/rinha-de-backend-2023-q3/stress-test/user-files/results/${{ env.GATLING_OUTPUT_FOLDER }}
          destination_dir: ${{ env.GATLING_OUTPUT_FOLDER }}
      - run: echo "https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }}" >> "${GITHUB_STEP_SUMMARY}"
