name: Lint Build Test

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: .
          version: latest

  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: make tests
  smoke_test:
    name: Smoke test
    runs-on: ubuntu-20.04
    steps:
      - run: make compose-up
      - name: smoke test
        run: curl -o /dev/null -s --retry 0 --head http://localhost:9999/contagem-pessoas || exit 1
      - run: echo "https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }}" >> "${GITHUB_STEP_SUMMARY}"
  login:
    name: Login to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
  build-image:
    runs-on: ubuntu-latest
    env:
      tag: stable
    steps:
      - run: ./scripts/build-image.sh

